services:
  backend:
    build:
      context: ./backend
    container_name: symfony_app
    volumes:
      - ./backend:/var/www/symfony
      - ./backend/.env:/var/www/symfony/.env
    ports:
      - "${BACKEND_PORT}:9000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - ./backend:/var/www/symfony
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules  # Exclude node_modules from host
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


  messenger_worker:
    build:
      context: ./backend
    container_name: symfony_messenger_worker
    command: php bin/console messenger:consume async -vv
    depends_on:
      - backend
    restart: always
    volumes:
      - ./backend:/var/www/symfony


volumes:
  db_data: